module.exports = {
  REST_PORT: 8080,
  REST_HOST: 'http://localhost',
  REST_API_PATH: '/data/v2',
  SESSION_TIMEOUT: 20 * 60 * 1000,
  ROOT_DIR: __dirname,
  SQL_HOST: 'localhost',
  DB_NAME: 'sistrac',
  SQL_USER: 'root',
  SQL_PASSWORD: '',
  SECRET: 'Sistrac clave secreta: pepino',
  COOKIE_NAME: 'user',
  APP_HOST: 'http://localhost',
  APP_PORT: '3000',
};
