// flow-typed signature: 7881fddd17e922ebd6ecbb2cd905e2fc
// flow-typed version: <<STUB>>/@devasatyam/controls_v^1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@devasatyam/controls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@devasatyam/controls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@devasatyam/controls/dist/70cd182680742140ab57bab1511a1c60' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/jest.config' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Button/Button' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Button/ButtonGroup' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Button/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/DataTable/DataTable' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/DataTable/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/DataTable/TableCol' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/Checkbox' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/Field' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/FormButtons' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/Radio' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/RenderField' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/Select' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Form/TextInput' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Grid/Col' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Grid/Grid' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Grid/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Grid/Row' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Jumbotron/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Alert' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Body' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Confirm' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Footer' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Header' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Modal' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/Prompt' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/withAlert' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/withConfirm' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Modal/withPrompt' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Button' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Divider' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Group' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Item' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Menu' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/NavBar' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/NavBar/Search' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Table/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Table/Table' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Tabs/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Tabs/Tab' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/Tabs/Tabs' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/lib/utils/isPlainClick' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/setupTests' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Button/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Button/Button' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Button/ButtonGroup' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Button/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/DataTable/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/DataTable/DataTable' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/DataTable/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/DataTable/TableCol' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/Checkbox' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/Field' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/FormButtons' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/Radio' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/RenderField' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/Select' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Form/TextInput' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Grid/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Grid/Col' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Grid/Grid' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Grid/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Grid/Row' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Jumbotron/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Jumbotron/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Alert' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Body' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Confirm' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Footer' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Header' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Modal' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/Prompt' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/withAlert' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/withConfirm' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Modal/withPrompt' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/__tests__/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/__tests__/NavBar' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Button' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Divider' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Group' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Item' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Menu' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/NavBar' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/NavBar/Search' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Table/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Table/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Table/Table' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Tabs/_example' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Tabs/index' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Tabs/Tab' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/Tabs/Tabs' {
  declare module.exports: any;
}

declare module '@devasatyam/controls/src/utils/isPlainClick' {
  declare module.exports: any;
}

// Filename aliases
declare module '@devasatyam/controls/dist/70cd182680742140ab57bab1511a1c60.js' {
  declare module.exports: $Exports<'@devasatyam/controls/dist/70cd182680742140ab57bab1511a1c60'>;
}
declare module '@devasatyam/controls/index' {
  declare module.exports: $Exports<'@devasatyam/controls'>;
}
declare module '@devasatyam/controls/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls'>;
}
declare module '@devasatyam/controls/jest.config.js' {
  declare module.exports: $Exports<'@devasatyam/controls/jest.config'>;
}
declare module '@devasatyam/controls/lib/Button/Button.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Button/Button'>;
}
declare module '@devasatyam/controls/lib/Button/ButtonGroup.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Button/ButtonGroup'>;
}
declare module '@devasatyam/controls/lib/Button/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Button/index'>;
}
declare module '@devasatyam/controls/lib/DataTable/DataTable.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/DataTable/DataTable'>;
}
declare module '@devasatyam/controls/lib/DataTable/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/DataTable/index'>;
}
declare module '@devasatyam/controls/lib/DataTable/TableCol.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/DataTable/TableCol'>;
}
declare module '@devasatyam/controls/lib/Form/Checkbox.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/Checkbox'>;
}
declare module '@devasatyam/controls/lib/Form/Field.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/Field'>;
}
declare module '@devasatyam/controls/lib/Form/FormButtons.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/FormButtons'>;
}
declare module '@devasatyam/controls/lib/Form/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/index'>;
}
declare module '@devasatyam/controls/lib/Form/Radio.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/Radio'>;
}
declare module '@devasatyam/controls/lib/Form/RenderField.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/RenderField'>;
}
declare module '@devasatyam/controls/lib/Form/Select.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/Select'>;
}
declare module '@devasatyam/controls/lib/Form/TextInput.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Form/TextInput'>;
}
declare module '@devasatyam/controls/lib/Grid/Col.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Grid/Col'>;
}
declare module '@devasatyam/controls/lib/Grid/Grid.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Grid/Grid'>;
}
declare module '@devasatyam/controls/lib/Grid/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Grid/index'>;
}
declare module '@devasatyam/controls/lib/Grid/Row.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Grid/Row'>;
}
declare module '@devasatyam/controls/lib/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/index'>;
}
declare module '@devasatyam/controls/lib/Jumbotron/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Jumbotron/index'>;
}
declare module '@devasatyam/controls/lib/Modal/Alert.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Alert'>;
}
declare module '@devasatyam/controls/lib/Modal/Body.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Body'>;
}
declare module '@devasatyam/controls/lib/Modal/Confirm.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Confirm'>;
}
declare module '@devasatyam/controls/lib/Modal/Footer.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Footer'>;
}
declare module '@devasatyam/controls/lib/Modal/Header.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Header'>;
}
declare module '@devasatyam/controls/lib/Modal/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/index'>;
}
declare module '@devasatyam/controls/lib/Modal/Modal.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Modal'>;
}
declare module '@devasatyam/controls/lib/Modal/Prompt.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/Prompt'>;
}
declare module '@devasatyam/controls/lib/Modal/withAlert.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/withAlert'>;
}
declare module '@devasatyam/controls/lib/Modal/withConfirm.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/withConfirm'>;
}
declare module '@devasatyam/controls/lib/Modal/withPrompt.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Modal/withPrompt'>;
}
declare module '@devasatyam/controls/lib/NavBar/Button.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Button'>;
}
declare module '@devasatyam/controls/lib/NavBar/Divider.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Divider'>;
}
declare module '@devasatyam/controls/lib/NavBar/Group.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Group'>;
}
declare module '@devasatyam/controls/lib/NavBar/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/index'>;
}
declare module '@devasatyam/controls/lib/NavBar/Item.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Item'>;
}
declare module '@devasatyam/controls/lib/NavBar/Menu.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Menu'>;
}
declare module '@devasatyam/controls/lib/NavBar/NavBar.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/NavBar'>;
}
declare module '@devasatyam/controls/lib/NavBar/Search.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/NavBar/Search'>;
}
declare module '@devasatyam/controls/lib/Table/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Table/index'>;
}
declare module '@devasatyam/controls/lib/Table/Table.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Table/Table'>;
}
declare module '@devasatyam/controls/lib/Tabs/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Tabs/index'>;
}
declare module '@devasatyam/controls/lib/Tabs/Tab.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Tabs/Tab'>;
}
declare module '@devasatyam/controls/lib/Tabs/Tabs.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/Tabs/Tabs'>;
}
declare module '@devasatyam/controls/lib/utils/isPlainClick.js' {
  declare module.exports: $Exports<'@devasatyam/controls/lib/utils/isPlainClick'>;
}
declare module '@devasatyam/controls/setupTests.js' {
  declare module.exports: $Exports<'@devasatyam/controls/setupTests'>;
}
declare module '@devasatyam/controls/src/Button/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Button/_example'>;
}
declare module '@devasatyam/controls/src/Button/Button.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Button/Button'>;
}
declare module '@devasatyam/controls/src/Button/ButtonGroup.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Button/ButtonGroup'>;
}
declare module '@devasatyam/controls/src/Button/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Button/index'>;
}
declare module '@devasatyam/controls/src/DataTable/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/DataTable/_example'>;
}
declare module '@devasatyam/controls/src/DataTable/DataTable.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/DataTable/DataTable'>;
}
declare module '@devasatyam/controls/src/DataTable/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/DataTable/index'>;
}
declare module '@devasatyam/controls/src/DataTable/TableCol.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/DataTable/TableCol'>;
}
declare module '@devasatyam/controls/src/Form/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/_example'>;
}
declare module '@devasatyam/controls/src/Form/Checkbox.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/Checkbox'>;
}
declare module '@devasatyam/controls/src/Form/Field.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/Field'>;
}
declare module '@devasatyam/controls/src/Form/FormButtons.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/FormButtons'>;
}
declare module '@devasatyam/controls/src/Form/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/index'>;
}
declare module '@devasatyam/controls/src/Form/Radio.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/Radio'>;
}
declare module '@devasatyam/controls/src/Form/RenderField.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/RenderField'>;
}
declare module '@devasatyam/controls/src/Form/Select.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/Select'>;
}
declare module '@devasatyam/controls/src/Form/TextInput.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Form/TextInput'>;
}
declare module '@devasatyam/controls/src/Grid/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Grid/_example'>;
}
declare module '@devasatyam/controls/src/Grid/Col.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Grid/Col'>;
}
declare module '@devasatyam/controls/src/Grid/Grid.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Grid/Grid'>;
}
declare module '@devasatyam/controls/src/Grid/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Grid/index'>;
}
declare module '@devasatyam/controls/src/Grid/Row.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Grid/Row'>;
}
declare module '@devasatyam/controls/src/index.js' {
  declare module.exports: $Exports<'@devasatyam/controls/src/index'>;
}
declare module '@devasatyam/controls/src/Jumbotron/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Jumbotron/_example'>;
}
declare module '@devasatyam/controls/src/Jumbotron/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Jumbotron/index'>;
}
declare module '@devasatyam/controls/src/Modal/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/_example'>;
}
declare module '@devasatyam/controls/src/Modal/Alert.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Alert'>;
}
declare module '@devasatyam/controls/src/Modal/Body.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Body'>;
}
declare module '@devasatyam/controls/src/Modal/Confirm.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Confirm'>;
}
declare module '@devasatyam/controls/src/Modal/Footer.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Footer'>;
}
declare module '@devasatyam/controls/src/Modal/Header.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Header'>;
}
declare module '@devasatyam/controls/src/Modal/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/index'>;
}
declare module '@devasatyam/controls/src/Modal/Modal.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Modal'>;
}
declare module '@devasatyam/controls/src/Modal/Prompt.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/Prompt'>;
}
declare module '@devasatyam/controls/src/Modal/withAlert.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/withAlert'>;
}
declare module '@devasatyam/controls/src/Modal/withConfirm.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/withConfirm'>;
}
declare module '@devasatyam/controls/src/Modal/withPrompt.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Modal/withPrompt'>;
}
declare module '@devasatyam/controls/src/NavBar/__tests__/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/__tests__/index'>;
}
declare module '@devasatyam/controls/src/NavBar/__tests__/NavBar.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/__tests__/NavBar'>;
}
declare module '@devasatyam/controls/src/NavBar/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/_example'>;
}
declare module '@devasatyam/controls/src/NavBar/Button.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Button'>;
}
declare module '@devasatyam/controls/src/NavBar/Divider.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Divider'>;
}
declare module '@devasatyam/controls/src/NavBar/Group.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Group'>;
}
declare module '@devasatyam/controls/src/NavBar/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/index'>;
}
declare module '@devasatyam/controls/src/NavBar/Item.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Item'>;
}
declare module '@devasatyam/controls/src/NavBar/Menu.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Menu'>;
}
declare module '@devasatyam/controls/src/NavBar/NavBar.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/NavBar'>;
}
declare module '@devasatyam/controls/src/NavBar/Search.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/NavBar/Search'>;
}
declare module '@devasatyam/controls/src/Table/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Table/_example'>;
}
declare module '@devasatyam/controls/src/Table/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Table/index'>;
}
declare module '@devasatyam/controls/src/Table/Table.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Table/Table'>;
}
declare module '@devasatyam/controls/src/Tabs/_example.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Tabs/_example'>;
}
declare module '@devasatyam/controls/src/Tabs/index.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Tabs/index'>;
}
declare module '@devasatyam/controls/src/Tabs/Tab.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Tabs/Tab'>;
}
declare module '@devasatyam/controls/src/Tabs/Tabs.jsx' {
  declare module.exports: $Exports<'@devasatyam/controls/src/Tabs/Tabs'>;
}
declare module '@devasatyam/controls/src/utils/isPlainClick.js' {
  declare module.exports: $Exports<'@devasatyam/controls/src/utils/isPlainClick'>;
}
