// flow-typed signature: 6cb4187f11d0598969d311d4f73a15b6
// flow-typed version: <<STUB>>/bootswatch_v^4.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootswatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootswatch' {
  declare module.exports: any;
}
