// flow-typed signature: 7cd5774d8aa03e716931e5ea8db76121
// flow-typed version: <<STUB>>/parse-dms_v0.0.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-dms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-dms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-dms/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-dms/index' {
  declare module.exports: $Exports<'parse-dms'>;
}
declare module 'parse-dms/index.js' {
  declare module.exports: $Exports<'parse-dms'>;
}
declare module 'parse-dms/test/index.js' {
  declare module.exports: $Exports<'parse-dms/test/index'>;
}
